{
 "title": "dashboard part7",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Процент загрузки ЦПУ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Доступная оперативная память",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество активных операций ввода/вывода на жестком диске",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=\"sda\"}[5m]) * 300 + rate(node_disk_writes_completed_total{device=\"sda\"}[5m]) * 300",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Свободное место на жестком диске",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/mapper/ubuntu--vg-ubuntu--lv\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}